version: "3.4"
services:
  pg:
    image: postgres:17.2
    restart: on-failure
    env_file: .env
    expose:
      - 5432
    volumes:
      - ./data/postgresql/:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 1s
      timeout: 3s
      retries: 30

  api:
    build:
      context: .
    depends_on:
      - pg
    user: "node"
    env_file: .env
    ports:
      - 4000:4000
    command: ["npm", "run", "start"]
