# Copyright 2023. The Tari Project
# SPDX-License-Identifier: BSD-3-Clause

wasm:
	wasm-pack build .

wasm-node:
	wasm-pack build --target nodejs -d tari_chk_sig_js .

wasm-test:
	wasm-pack test --node
